{{- if .Values.logging.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.loggingNamespace }}
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.loggingNamespace }}
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"
            - name: SERVER_PUBLICBASEURL
              value: "http://localhost:8080/kibana"
            # Force bind address/port explicitly
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5601"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: XPACK_SECURITY_ENROLLMENT_ENABLED
              value: "false"
{{- end -}}