apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flightops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "${GIT_URL}"
    targetRevision: "${GIT_REVISION}"
    path: "${GIT_PATH}"
    kustomize:
      images:
        - frontend=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/flight-ops/frontend:latest
        - backend=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/flight-ops/backend:latest
        - crawler=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/flight-ops/crawler:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: "${NAME_SPACE}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
