apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: flightops-dev
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
  