apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "derek"
  MYSQL_DATABASE: "flight_ops"
  BACKEND_DB_USER: "backend_ro"
  BACKEND_DB_PASSWORD: "backend_ro_pw"
  CRAWLER_DB_USER: "crawler_rw"
  CRAWLER_DB_PASSWORD: "crawler_rw_pw"
