apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: flightops
    valuesFile: values-prod.yaml
    releaseName: flightops-prod

patches:
  - path: app/patches/backend-replicas.yaml