apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/app

namespace: flightops-dev

# Add env labels but DO NOT change selectors (prevents immutable selector errors)
labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeSelectors: false
    includeTemplates: true

patches:
  - path: patches/backend-resources.yaml
  - path: patches/frontend-resources.yaml
  - path: patches/mysql-storage.yaml
  - path: patches/crawler-cleanup.yaml
